development:
  adapter: postgresql
  encoding: unicode
  database: tripraze_development
  pool: 5
  username: rigelstpierre
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: tripraze_test
  pool: 5
  username: rigelstpierre
  password:
